export type DrinkCategory =
  | 'champagne'
  | 'whisky'
  | 'cognac'
  | 'wines'
  | 'spirits'
  | 'cocktails'
  | 'mixers'
  | 'party-packs';

export type DrinkProduct = {
  slug: string;
  name: string;
  brand?: string;
  origin?: string;
  category: DrinkCategory;
  abv: number;
  volume: string;
  priceNgn: number;
  tagline: string;
  description: string;
  image?: string;
  /** Extra shots of the same bottle — box, back label, serve. Feeds the PDP gallery. */
  images?: string[];
  packImages?: string[];
  includes?: string[];
  featured?: boolean;
  deal?: boolean;
  partyPack?: boolean;
  /** Cheap SKU for checkout tests — hidden from party auto-plans. */
  sample?: boolean;
  servesHint?: string;
};

export const SAMPLE_PAYMENT_SLUG = 'convivia-cocktail';

/** Prefer Azure when `NEXT_PUBLIC_AZURE_DRINK_BASE` is set (private containers need SAS). */
const AZURE_DRINK_BASE = (process.env.NEXT_PUBLIC_AZURE_DRINK_BASE || '').replace(/\/$/, '');
const AZURE_DRINK_SAS = (process.env.NEXT_PUBLIC_AZURE_DRINK_SAS || '').replace(/^\?/, '');
const pics = (file: string) => {
  if (!AZURE_DRINK_BASE) return `/DrinkPics/${file}`;
  const url = `${AZURE_DRINK_BASE}/${file}`;
  return AZURE_DRINK_SAS ? `${url}?${AZURE_DRINK_SAS}` : url;
};

export const CATEGORY_LABELS: Record<DrinkCategory, string> = {
  champagne: 'Champagne',
  whisky: 'Whisky',
  cognac: 'Cognac',
  wines: 'Wines',
  spirits: 'Spirits',
  cocktails: 'Canned cocktails',
  mixers: 'Mixers & Soft',
  'party-packs': 'Party packs',
};

export const CATEGORIES: DrinkCategory[] = [
  'champagne',
  'whisky',
  'cognac',
  'wines',
  'spirits',
  'cocktails',
  'mixers',
  'party-packs',
];

/** Order-line `prefer_track` only accepts spirit | zero | mixed. Shop categories map onto that. */
export type PreferTrack = 'spirit' | 'zero' | 'mixed';

export function preferTrackForCategory(category: string): PreferTrack {
  if (category === 'mixers') return 'zero';
  if (category === 'cocktails' || category === 'party-packs') return 'mixed';
  return 'spirit';
}

export function formatNgn(amount: number): string {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    maximumFractionDigits: 0,
  }).format(amount);
}

export const DRINKS: DrinkProduct[] = [
  {
    slug: 'hennessy-vs',
    name: 'Hennessy VS',
    brand: 'Hennessy',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 78000,
    tagline: 'The unmistakable drop.',
    description: 'The Cognac Lagos parties still request by name.',
    image: pics('Hennessy-5-600x900.webp'),
    featured: true,
  },
  {
    slug: 'jameson-original',
    name: 'Jameson Original',
    brand: 'Jameson',
    origin: 'Ireland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 42000,
    tagline: 'Smooth Irish for the crew.',
    description: 'Triple-distilled Irish whiskey — mixable, shareable, always on the party list.',
    image: pics('Jatt-Jameson-1-600x900.webp'),
    featured: true,
  },
  {
    slug: 'johnnie-walker-black',
    name: 'Johnnie Walker Black Label',
    brand: 'Johnnie Walker',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 52000,
    tagline: '12-year blended Scotch.',
    description: 'The black label Lagos tables keep coming back to.',
    image: pics('Johnnie-Walker-1-600x900.webp'),
    featured: true,
  },
  {
    slug: 'ciroc-snap-frost',
    name: 'Cîroc Snap Frost',
    brand: 'Cîroc',
    origin: 'France',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 55000,
    tagline: 'Grape vodka for the booth.',
    description: 'Five-times distilled from French grapes — clean, club-ready.',
    image: pics('Ciroc-Vodka-600x900.webp'),
    featured: true,
  },
  {
    slug: 'moet-imperial',
    name: 'Moët & Chandon Impérial',
    brand: 'Moët & Chandon',
    origin: 'France',
    category: 'champagne',
    abv: 12,
    volume: '75CL',
    priceNgn: 185000,
    tagline: 'The club table classic.',
    description: 'Bright citrus and brioche — the bottle that opens the night on VI dancefloors and rooftop lounges.',
    image: pics('Moet-Champagne.jpg'),
    featured: true,
  },
  {
    slug: 'veuve-yellow-label',
    name: 'Veuve Clicquot Yellow Label',
    brand: 'Veuve Clicquot',
    origin: 'France',
    category: 'champagne',
    abv: 12,
    volume: '75CL',
    priceNgn: 210000,
    tagline: 'Orange label energy.',
    description: 'Full-bodied Champagne for birthday tables and lounge bottle service.',
    image: pics('Veuve-Clicquot-Yellow-Label.png'),
    featured: true,
    deal: true,
  },
  {
    slug: 'gh-mumm-cordon-rouge',
    name: 'G.H. Mumm Cordon Rouge',
    brand: 'G.H. Mumm',
    origin: 'France',
    category: 'champagne',
    abv: 12,
    volume: '75CL',
    priceNgn: 175000,
    tagline: 'Red sash on the table.',
    description: 'Pinot Noir–led Champagne — crisp apple, brioche, and that unmistakable red cordon.',
    image: pics('GH-Mumm-Champagne.jpeg'),
    featured: true,
  },
  {
    slug: 'jameson-black-barrel',
    name: 'Jameson Black Barrel',
    brand: 'Jameson',
    origin: 'Ireland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 58000,
    tagline: 'Hot deal · richer oak.',
    description: 'Double-charred barrels bring spice and vanilla — a lounge pour that punches above.',
    image: pics('Jameson-Black-Barrel-Whisky-70cl-1-600x900.webp'),
    deal: true,
  },
  {
    slug: 'glenmorangie-original',
    name: 'Glenmorangie Original',
    brand: 'Glenmorangie',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 72000,
    tagline: 'Single malt for late sets.',
    description: 'Floral Highland malt — soft enough for first-timers, serious enough for the host.',
    image: pics('glenmorangie-12-yr-70cl.jpeg'),
  },
  {
    slug: 'glenmorangie-lasanta',
    name: 'Glenmorangie Lasanta',
    brand: 'Glenmorangie',
    origin: 'Scotland',
    category: 'whisky',
    abv: 43,
    volume: '70CL',
    priceNgn: 85000,
    tagline: '12-year sherry cask finish.',
    description: 'Bourbon-matured, then finished in Oloroso and PX sherry casks.',
    image: pics('Glenmorange-3-600x900.webp'),
  },
  {
    slug: 'glenmorangie-signet',
    name: 'Glenmorangie Signet',
    brand: 'Glenmorangie',
    origin: 'Scotland',
    category: 'whisky',
    abv: 46,
    volume: '70CL',
    priceNgn: 280000,
    tagline: 'Chocolate-malt flex.',
    description: 'High-cocoa malt for hosts who want a conversation bottle.',
    image: pics('Glenmorangie-Signet-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'chivas-12',
    name: 'Chivas Regal 12 Year',
    brand: 'Chivas Regal',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 48000,
    tagline: 'Blended Scotch staple.',
    description: 'Honeyed, approachable 12-year blend for big crews.',
    image: pics('Chivas-Regal-12-Year-Old-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'chivas-18',
    name: 'Chivas Regal 18 Year',
    brand: 'Chivas Regal',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 125000,
    tagline: 'Gold-label night.',
    description: 'Richer, longer-aged Chivas for VIP tables.',
    image: pics('Chivas-Regal-18-Year-Old-Whisky-70cl-600x900.webp'),
    deal: true,
  },
  {
    slug: 'famous-grouse',
    name: 'The Famous Grouse',
    brand: 'The Famous Grouse',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 28000,
    tagline: 'Everyday Scotch.',
    description: 'The mixer-friendly blend that stretches a house party.',
    image: pics('Famous-Grouse-Scotch-Whiskey-70cl-600x900.webp'),
  },
  {
    slug: 'monkey-shoulder',
    name: 'Monkey Shoulder',
    brand: 'Monkey Shoulder',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 55000,
    tagline: 'Malt blend for cocktails.',
    description: 'Triple-malt Scotch built for mixing and sharing.',
    image: pics('Monkey-Shoulder-Blended-Malt-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'jack-daniels',
    name: "Jack Daniel's Old No. 7",
    brand: "Jack Daniel's",
    origin: 'USA',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 45000,
    tagline: 'Tennessee whiskey classic.',
    description: 'Charcoal-mellowed — cola, ice, and a long night.',
    image: pics('Jack-Daniels-1-600x900.webp'),
  },
  {
    slug: 'gentlemen-jack',
    name: "Gentleman Jack",
    brand: "Jack Daniel's",
    origin: 'USA',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 58000,
    tagline: 'Double-mellowed Jack.',
    description: 'Smoother Tennessee whiskey for sipping tables.',
    image: pics('JD-Gentlemens-Jack-Mini-600x900.webp'),
  },
  {
    slug: 'johnnie-walker-gold',
    name: 'Johnnie Walker Gold Label Reserve',
    brand: 'Johnnie Walker',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 145000,
    tagline: 'Honeyed reserve blend.',
    description: 'Master blender’s reserve — richer than Black, still a crowd pour.',
    image: pics('Johnnie-Walker-5-600x900.webp'),
  },
  {
    slug: 'johnnie-walker-green',
    name: 'Johnnie Walker Green Label',
    brand: 'Johnnie Walker',
    origin: 'Scotland',
    category: 'whisky',
    abv: 43,
    volume: '70CL',
    priceNgn: 110000,
    tagline: '15-year blended malt.',
    description: 'All-malt JW for hosts who want more than a blend.',
    image: pics('Johnnie-Walker-11-600x900.webp'),
  },
  {
    slug: 'johnnie-walker-blue',
    name: 'Johnnie Walker Blue Label',
    brand: 'Johnnie Walker',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 450000,
    tagline: 'The rare-blend flex.',
    description: 'A blend of the rarest JW stocks — birthday and close tables.',
    image: pics('Johnnie-Walker-10-600x900.webp'),
    featured: true,
  },
  {
    slug: 'glenfiddich-12',
    name: 'Glenfiddich 12 Year',
    brand: 'Glenfiddich',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 68000,
    tagline: 'Speyside gateway malt.',
    description: 'Pear and oak — the single malt most crews recognise.',
    image: pics('Glenfiddich-12-Year-Old-Whisky-5cl-600x900.webp'),
  },
  {
    slug: 'glenfiddich-gran-reserva',
    name: 'Glenfiddich Gran Reserva',
    brand: 'Glenfiddich',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 165000,
    tagline: 'Caribbean rum cask.',
    description: '21-year Speyside finished in rum casks.',
    image: pics('Glenfiddich_GrandReserva.webp'),
  },
  {
    slug: 'glenlivet-founders',
    name: "The Glenlivet Founder's Reserve",
    brand: 'The Glenlivet',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 62000,
    tagline: 'Speyside citrus.',
    description: 'Soft, fruity malt for first-time single-malt tables.',
    image: pics('The-Glenlivet-Founders-Reserve-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'glenlivet-12',
    name: 'The Glenlivet 12 Year',
    brand: 'The Glenlivet',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 68000,
    tagline: 'Classic Speyside 12.',
    description: 'Balanced orchard fruit and vanilla.',
    image: pics('The-Glenlivet-12-Year-Old-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'glenlivet-18',
    name: 'The Glenlivet 18 Year',
    brand: 'The Glenlivet',
    origin: 'Scotland',
    category: 'whisky',
    abv: 43,
    volume: '70CL',
    priceNgn: 155000,
    tagline: 'Longer Speyside pour.',
    description: 'Richer oak and spice for a quieter table.',
    image: pics('The-Glenlivet-18-Year-Old-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'macallan-12',
    name: 'The Macallan 12 Double Cask',
    brand: 'The Macallan',
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 185000,
    tagline: 'Sherry + American oak.',
    description: 'The Macallan most requested for Lagos birthdays.',
    image: pics('The-Macallan-12-Year-Old-Double-Cask-Whisky-70cl-600x900.webp'),
    featured: true,
  },
  {
    slug: 'macallan-18',
    name: 'The Macallan 18 Year',
    brand: 'The Macallan',
    origin: 'Scotland',
    category: 'whisky',
    abv: 43,
    volume: '70CL',
    priceNgn: 850000,
    tagline: 'The serious Macallan.',
    description: 'Long sherry-cask maturation — a host bottle.',
    image: pics('The-Macallan-18-Year-old-600x900.webp'),
  },
  {
    slug: 'macallan-25',
    name: 'The Macallan 25 Sherry Oak',
    brand: 'The Macallan',
    origin: 'Scotland',
    category: 'whisky',
    abv: 43,
    volume: '70CL',
    priceNgn: 2800000,
    tagline: 'Collector’s sherry oak.',
    description: '25-year Sherry Oak — for the table that wants a statement.',
    image: pics('The-Macallan-25-Year-Old-Sherry-Oak-Whisky-70cl-600x900.webp'),
  },
  {
    slug: 'ballantines-finest',
    name: "Ballantine's Finest",
    brand: "Ballantine's",
    origin: 'Scotland',
    category: 'whisky',
    abv: 40,
    volume: '70CL',
    priceNgn: 38000,
    tagline: 'Blended Scotch staple.',
    description: 'Approachable Scotch for big crews and long nights.',
    image: pics('Ballantines.avif'),
  },
  {
    slug: 'martell-vs',
    name: 'Martell VS',
    brand: 'Martell',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 65000,
    tagline: 'Cognac for the toast.',
    description: 'Fruit-forward Cognac built for VIP tables and after-party pours.',
    image: pics('Martell-3-1-600x900.webp'),
    featured: true,
  },
  {
    slug: 'martell-blue-swift',
    name: 'Martell Blue Swift',
    brand: 'Martell',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 95000,
    tagline: 'Bourbon-finished flex.',
    description: 'Cognac finished in bourbon casks — smooth, modern, club-ready.',
    image: pics('Martell-Blue-Swift.jpg'),
    deal: true,
  },
  {
    slug: 'martell-xo',
    name: 'Martell XO',
    brand: 'Martell',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 320000,
    tagline: 'XO for the close table.',
    description: 'Longer-aged Martell — dried fruit and spice.',
    image: pics('Martell-XO-Cognac-70cl-534x800.webp'),
  },
  {
    slug: 'hennessy-vsop',
    name: 'Hennessy VSOP',
    brand: 'Hennessy',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 125000,
    tagline: 'Privilege pour.',
    description: 'A step up from VS — still the name on the list.',
    image: pics('Hennessy-VSOP-600x900.webp'),
    deal: true,
  },
  {
    slug: 'hennessy-xo',
    name: 'Hennessy XO',
    brand: 'Hennessy',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 280000,
    tagline: 'The XO statement.',
    description: 'Deep, spicy Cognac for birthday and close tables.',
    image: pics('Hennessy-XO-600x900.jpg'),
    featured: true,
  },
  {
    slug: 'remy-martin-vsop',
    name: 'Rémy Martin VSOP',
    brand: 'Rémy Martin',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 98000,
    tagline: 'Fine Champagne VSOP.',
    description: 'Fruit and vanilla — a reliable VIP pour.',
    image: pics('Remy-Martin-VSOP-600x900.webp'),
  },
  {
    slug: 'remy-martin-1738',
    name: 'Rémy Martin 1738 Accord Royal',
    brand: 'Rémy Martin',
    origin: 'France',
    category: 'cognac',
    abv: 40,
    volume: '70CL',
    priceNgn: 145000,
    tagline: 'Between VSOP and XO.',
    description: 'Richer Fine Champagne Cognac with cocoa and spice.',
    image: pics('Remy-Martin-6-600x900.webp'),
  },
  {
    slug: 'casamigos-reposado',
    name: 'Casamigos Reposado',
    brand: 'Casamigos',
    origin: 'Mexico',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 110000,
    tagline: 'Tequila for the terrace.',
    description: 'Oak-aged reposado — sip neat or build margaritas for the whole lounge booth.',
    featured: true,
  },
  {
    slug: 'casamigos-anejo',
    name: 'Casamigos Añejo',
    brand: 'Casamigos',
    origin: 'Mexico',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 135000,
    tagline: 'Longer-aged Casamigos.',
    description: 'Añejo for sipping tables and slower nights.',
    image: pics('Casamigos-Anejo-Tequila-70cl-600x900.webp'),
  },
  {
    slug: 'clase-azul-reposado',
    name: 'Clase Azul Reposado',
    brand: 'Clase Azul',
    origin: 'Mexico',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 280000,
    tagline: 'The ceramic bottle.',
    description: 'The tequila that photographs itself — gift and table piece.',
    image: pics('ClaseAzulReprosado-600x900.webp'),
    featured: true,
  },
  {
    slug: 'don-julio-1942',
    name: 'Don Julio 1942',
    brand: 'Don Julio',
    origin: 'Mexico',
    category: 'spirits',
    abv: 38,
    volume: '70CL',
    priceNgn: 180000,
    tagline: 'Añejo for the close table.',
    description: 'The tequila Lagos still orders when the night turns serious.',
    image: pics('Don-Julio-1942-Tequila-70cl-600x900.webp'),
    featured: true,
  },
  {
    slug: 'absolut-vodka',
    name: 'Absolut Vodka',
    brand: 'Absolut',
    origin: 'Sweden',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 28000,
    tagline: 'The mixer workhorse.',
    description: 'Clean Swedish vodka for punch bowls and long mixes.',
    image: pics('Absolut-3-600x900.webp'),
  },
  {
    slug: 'absolut-citron',
    name: 'Absolut Citron',
    brand: 'Absolut',
    origin: 'Sweden',
    category: 'spirits',
    abv: 40,
    volume: '70CL',
    priceNgn: 30000,
    tagline: 'Lemon vodka twist.',
    description: 'Citrus vodka for day parties and spritz-style mixes.',
    image: pics('Absolut-1-600x900.webp'),
  },
  {
    slug: 'ciroc-red-berry',
    name: 'Cîroc Red Berry',
    brand: 'Cîroc',
    origin: 'France',
    category: 'spirits',
    abv: 37.5,
    volume: '70CL',
    priceNgn: 58000,
    tagline: 'Berry-flavoured Cîroc.',
    description: 'The red bottle for mixers and bottle service.',
    image: pics('Ciroc-5-600x900.webp'),
  },
  {
    slug: 'ciroc-mango',
    name: 'Cîroc Mango',
    brand: 'Cîroc',
    origin: 'France',
    category: 'spirits',
    abv: 37.5,
    volume: '70CL',
    priceNgn: 58000,
    tagline: 'Mango-flavoured Cîroc.',
    description: 'Tropical Cîroc for rooftop and day-to-night sets.',
    image: pics('Ciroc-7-600x900.webp'),
  },
  {
    slug: 'chardonnay-house',
    name: 'House Chardonnay',
    brand: 'Convivia',
    origin: 'France',
    category: 'wines',
    abv: 13,
    volume: '75CL',
    priceNgn: 28000,
    tagline: 'White for the balcony.',
    description: 'Crisp, citrusy white — perfect with outdoor hangouts before the club.',
  },
  {
    slug: 'prosecco-brut',
    name: 'Prosecco Brut',
    brand: 'Convivia',
    origin: 'Italy',
    category: 'wines',
    abv: 11,
    volume: '75CL',
    priceNgn: 32000,
    tagline: 'Sparkle without the wait.',
    description: 'Italian bubbles for day parties, rooftops, and brunch-to-night transitions.',
    featured: true,
  },
  {
    slug: SAMPLE_PAYMENT_SLUG,
    name: 'Convivia Cocktail',
    brand: 'Convivia',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 5,
    volume: '33CL',
    priceNgn: 500,
    tagline: 'House pour, cold and ready.',
    description: 'Convivia house cocktail in a can — light, citrus-led, and easy to deliver for a small tab.',
  },
  {
    slug: 'smirnoff-ice-pack',
    name: 'Smirnoff Ice · 6 cans',
    brand: 'Smirnoff Ice',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 5,
    volume: '33CL × 6',
    priceNgn: 7200,
    tagline: 'The canned classic.',
    description: 'Lemon-lime vodka cocktail in a can — cooler bags, beach days, day parties.',
  },
  {
    slug: 'flying-fish-pack',
    name: 'Flying Fish · 6 cans',
    brand: 'Flying Fish',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 4.5,
    volume: '33CL × 6',
    priceNgn: 6500,
    tagline: 'Citrus smash in a can.',
    description: 'Flavoured malt cocktail — light, cold, and built for outdoor sets.',
    deal: true,
  },
  {
    slug: 'brutal-fruit-pack',
    name: 'Brutal Fruit · 6 cans',
    brand: 'Brutal Fruit',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 5,
    volume: '33CL × 6',
    priceNgn: 7800,
    tagline: 'Berry fizz, ready to pour.',
    description: 'Sparkling fruit cocktail cans for rooftops and after-beach hangs.',
  },
  {
    slug: 'hunters-dry-pack',
    name: "Hunter's Dry · 6 cans",
    brand: "Hunter's",
    origin: 'South Africa',
    category: 'cocktails',
    abv: 5,
    volume: '33CL × 6',
    priceNgn: 8000,
    tagline: 'Dry cider energy.',
    description: 'Crisp canned cider-cocktail hybrid — day party staple.',
  },
  {
    slug: 'ace-berry-pack',
    name: 'Ace Berry · 6 cans',
    brand: 'Ace',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 5,
    volume: '33CL × 6',
    priceNgn: 6800,
    tagline: 'Berry can for the cooler.',
    description: 'Ready-to-drink berry cocktail — easy volume for crews.',
  },
  {
    slug: 'orijin-rtd-pack',
    name: 'Orijin RTD · 6 cans',
    brand: 'Orijin',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 6,
    volume: '33CL × 6',
    priceNgn: 7500,
    tagline: 'Bitters, canned.',
    description: 'Herbal bitters cocktail in a can — Lagos night starter.',
    featured: true,
  },
  {
    slug: 'desperados-pack',
    name: 'Desperados · 6 cans',
    brand: 'Desperados',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 5.9,
    volume: '33CL × 6',
    priceNgn: 8200,
    tagline: 'Tequila-twist malt.',
    description: 'Tequila-flavoured malt cocktail cans for terrace tables.',
  },
  {
    slug: 'breezer-peach-pack',
    name: 'Breezer Peach · 6 bottles',
    brand: 'Breezer',
    origin: 'Nigeria',
    category: 'cocktails',
    abv: 4,
    volume: '27.5CL × 6',
    priceNgn: 9000,
    tagline: 'Peach vodka cooler.',
    description: 'Ready-to-drink peach cocktail — sweet, cold, party-pack friendly.',
  },
  {
    slug: 'tiger-cranberry',
    name: 'Tiger Cranberry',
    brand: 'Tiger',
    origin: 'Nigeria',
    category: 'mixers',
    abv: 0,
    volume: '33CL × 6',
    priceNgn: 8500,
    tagline: 'Energy for the outdoor set.',
    description: 'Zero-ABV mixer pack — keep the circle hydrated between pours.',
  },
  {
    slug: 'schweppes-tonic-pack',
    name: 'Schweppes Tonic Pack',
    brand: 'Schweppes',
    origin: 'Nigeria',
    category: 'mixers',
    abv: 0,
    volume: '33CL × 12',
    priceNgn: 12000,
    tagline: 'Gin’s best friend.',
    description: 'Tonic six-packs doubled for party volume.',
  },
  {
    slug: 'party-pack-10',
    name: 'Party Pack · 10',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 0,
    volume: '4 bottles',
    priceNgn: 185000,
    tagline: 'Small crew, sorted.',
    description: 'Jameson, Hennessy VS, Absolut, and Cîroc — sized for ~10 guests. Mixers sold beside.',
    partyPack: true,
    featured: true,
    servesHint: '~10 guests',
    packImages: [
      pics('Jatt-Jameson-1-600x900.webp'),
      pics('Hennessy-5-600x900.webp'),
      pics('Absolut-3-600x900.webp'),
      pics('Ciroc-Vodka-600x900.webp'),
    ],
    includes: ['Jameson Original', 'Hennessy VS', 'Absolut Vodka', 'Cîroc Snap Frost'],
  },
  {
    slug: 'party-pack-20',
    name: 'Party Pack · 20',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 0,
    volume: '4 bottles',
    priceNgn: 345000,
    tagline: 'House party ready.',
    description: 'Black Label, Hennessy VSOP, Casamigos Añejo, and Cîroc Red Berry for ~20 guests.',
    partyPack: true,
    deal: true,
    servesHint: '~20 guests',
    packImages: [
      pics('Johnnie-Walker-1-600x900.webp'),
      pics('Hennessy-VSOP-600x900.webp'),
      pics('Casamigos-Anejo-Tequila-70cl-600x900.webp'),
      pics('Ciroc-5-600x900.webp'),
    ],
    includes: ['Johnnie Walker Black Label', 'Hennessy VSOP', 'Casamigos Añejo', 'Cîroc Red Berry'],
  },
  {
    slug: 'party-pack-50',
    name: 'Party Pack · 50',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 0,
    volume: '4 bottles',
    priceNgn: 780000,
    tagline: 'Club / lounge takeover.',
    description: 'Blue Label, Hennessy XO, Don Julio 1942, and Macallan 12 — host locks the crew cart.',
    partyPack: true,
    servesHint: '~50 guests',
    packImages: [
      pics('Johnnie-Walker-10-600x900.webp'),
      pics('Hennessy-XO-600x900.jpg'),
      pics('Don-Julio-1942-Tequila-70cl-600x900.webp'),
      pics('The-Macallan-12-Year-Old-Double-Cask-Whisky-70cl-600x900.webp'),
    ],
    includes: ['Johnnie Walker Blue Label', 'Hennessy XO', 'Don Julio 1942', 'The Macallan 12'],
  },
  {
    slug: 'whisky-table-pack',
    name: 'Whisky Table Pack',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 40,
    volume: '4 bottles',
    priceNgn: 198000,
    tagline: 'Four malts, one table.',
    description: 'Black Label, Jameson, Chivas 12, and Monkey Shoulder — the whisky rail for a house party.',
    partyPack: true,
    servesHint: '~12 guests',
    packImages: [
      pics('Johnnie-Walker-1-600x900.webp'),
      pics('Jatt-Jameson-1-600x900.webp'),
      pics('Chivas-Regal-12-Year-Old-Whisky-70cl-600x900.webp'),
      pics('Monkey-Shoulder-Blended-Malt-Whisky-70cl-600x900.webp'),
    ],
    includes: ['Johnnie Walker Black Label', 'Jameson Original', 'Chivas Regal 12', 'Monkey Shoulder'],
  },
  {
    slug: 'cognac-vip-pack',
    name: 'Cognac VIP Pack',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 40,
    volume: '3 bottles',
    priceNgn: 268000,
    tagline: 'VS · VSOP · 1738.',
    description: 'Hennessy VS, Martell VS, and Rémy Martin 1738 for the close table.',
    partyPack: true,
    featured: true,
    servesHint: '~8 guests',
    packImages: [
      pics('Hennessy-5-600x900.webp'),
      pics('Martell-3-1-600x900.webp'),
      pics('Remy-Martin-6-600x900.webp'),
    ],
    includes: ['Hennessy VS', 'Martell VS', 'Rémy Martin 1738'],
  },
  {
    slug: 'tequila-terrace-pack',
    name: 'Tequila Terrace Pack',
    brand: 'Convivia',
    category: 'party-packs',
    abv: 40,
    volume: '3 bottles',
    priceNgn: 595000,
    tagline: 'Añejo night, ceramic flex.',
    description: 'Casamigos Añejo, Don Julio 1942, and Clase Azul Reposado — terrace and booth energy.',
    partyPack: true,
    deal: true,
    servesHint: '~10 guests',
    packImages: [
      pics('Casamigos-Anejo-Tequila-70cl-600x900.webp'),
      pics('Don-Julio-1942-Tequila-70cl-600x900.webp'),
      pics('ClaseAzulReprosado-600x900.webp'),
    ],
    includes: ['Casamigos Añejo', 'Don Julio 1942', 'Clase Azul Reposado'],
  },
];

export function getDrinkBySlug(slug: string): DrinkProduct | undefined {
  return DRINKS.find((d) => d.slug === slug);
}

export function drinksByCategory(category: DrinkCategory): DrinkProduct[] {
  return DRINKS.filter((d) => d.category === category);
}

export function searchDrinks(query: string): DrinkProduct[] {
  const q = query.trim().toLowerCase();
  if (!q) return DRINKS;
  return DRINKS.filter(
    (d) =>
      d.name.toLowerCase().includes(q) ||
      (d.brand && d.brand.toLowerCase().includes(q)) ||
      (d.origin && d.origin.toLowerCase().includes(q)) ||
      d.category.includes(q) ||
      CATEGORY_LABELS[d.category].toLowerCase().includes(q) ||
      d.tagline.toLowerCase().includes(q)
  );
}

/**
 * Every shot we hold of a product, main image first. The PDP gallery renders a
 * thumbnail rail only when there is genuinely more than one — no filler frames.
 */
export function galleryFor(product: DrinkProduct): string[] {
  const shots = [product.image, ...(product.images ?? []), ...(product.packImages ?? [])];
  return [...new Set(shots.filter((s): s is string => Boolean(s)))];
}

export type SizeOption = { slug: string; volume: string; priceNgn: number };

/**
 * Other volumes of the same bottle that are actually stocked — a 50cl next to
 * a 70cl, say. Matched on brand plus the name with any volume suffix stripped,
 * so it only ever returns real SKUs the shopper can add to a cart.
 */
export function sizeOptionsFor(product: DrinkProduct): SizeOption[] {
  const family = (d: DrinkProduct) => `${d.brand ?? ''}|${d.name.replace(/\s*\d+\s*cl\b/i, '').trim().toLowerCase()}`;
  const key = family(product);
  return DRINKS.filter((d) => family(d) === key && d.category === product.category)
    .map((d) => ({ slug: d.slug, volume: d.volume, priceNgn: d.priceNgn }))
    .sort((a, b) => a.priceNgn - b.priceNgn);
}

/** Bottles a shopper looking at this one would plausibly consider next. */
export function relatedDrinks(product: DrinkProduct, limit = 3): DrinkProduct[] {
  const pool = DRINKS.filter((d) => d.slug !== product.slug && !d.partyPack && !d.sample);
  const sameBrand = pool.filter((d) => d.brand && d.brand === product.brand);
  const sameCategory = pool.filter((d) => d.category === product.category && d.brand !== product.brand);
  const nearestPrice = (a: DrinkProduct, b: DrinkProduct) =>
    Math.abs(a.priceNgn - product.priceNgn) - Math.abs(b.priceNgn - product.priceNgn);
  return [...sameBrand.sort(nearestPrice), ...sameCategory.sort(nearestPrice)].slice(0, limit);
}
