'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {authClient} from '@/lib/auth/client';
import {useUser} from '@/components/auth/AuthProvider';
import {LAUNCH_CITIES} from '@/lib/delivery/policy';
type Address={id:string;label:string;address_line1:string;city:string;area:string};
export default function AccountSettings(){const{user}=useUser();const[addresses,setAddresses]=useState<Address[]>([]);const[marketing,setMarketing]=useState(false);const[deletion,setDeletion]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const res=await fetch('/api/account/settings');const data=await res.json();if(!res.ok)throw new Error(data.error);setAddresses(data.addresses);setMarketing(data.preferences.marketing_email);setDeletion(!!data.preferences.deletion_requested_at);}catch(err){setMsg(err instanceof Error?err.message:'Could not load settings.');}},[]);useEffect(()=>{void load();},[load]);
  async function save(body:Record<string,unknown>){setBusy(true);try{const res=await fetch('/api/account/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();setMsg('Saved.');}catch(err){setMsg(err instanceof Error?err.message:'Could not save.');}finally{setBusy(false);}}
  function address(event:FormEvent<HTMLFormElement>){event.preventDefault();void save({action:'save-address',...Object.fromEntries(new FormData(event.currentTarget))});}
  const field='block w-full border rounded p-2 mt-1';
  return <div className="space-y-6"><p role="status">{msg}</p><section className="bg-white p-5 border rounded-xl"><h2 className="font-bold text-lg">Account</h2><p className="my-3">{user?.email}</p><form onSubmit={async event=>{event.preventDefault();const name=String(new FormData(event.currentTarget).get('name')||'');const result=await authClient.updateUser({name});setMsg(result.error?.message||'Name updated.');}} className="flex gap-2"><input name="name" aria-label="Full name" required defaultValue={user?.name||''} className={field}/><button className="btn-brand px-3">Save name</button></form><button className="mt-4 text-ember" onClick={async()=>{if(!user)return;const result=await authClient.sendVerificationEmail({email:user.email,callbackURL:new URL('/my-account',window.location.origin).toString()});setMsg(result.error?.message||'Verification email requested.');}}>Send email verification link</button></section>
    <section className="bg-white p-5 border rounded-xl"><h2 className="font-bold text-lg mb-4">Saved addresses</h2>{addresses.map(item=><div key={item.id} className="flex justify-between gap-3 border-t py-3"><span>{item.label} · {item.address_line1} · {item.area}, {item.city}</span><button disabled={busy} onClick={()=>save({action:'delete-address',id:item.id})}>Remove</button></div>)}<form onSubmit={address} className="grid sm:grid-cols-2 gap-3">{[['label','Address label'],['fullName','Recipient name'],['phone','Phone number'],['addressLine1','Street address'],['addressLine2','Landmark (optional)'],['area','Area']].map(([name,label])=><label key={name}>{label}<input name={name} required={name!=='addressLine2'} className={field}/></label>)}<label>City<select name="city" className={field}>{LAUNCH_CITIES.map(city=><option key={city}>{city}</option>)}</select></label><button disabled={busy} className="btn-brand px-4 py-2">Save address</button></form></section>
    <section className="bg-white p-5 border rounded-xl"><h2 className="font-bold text-lg">Preferences</h2><label className="block mt-4"><input type="checkbox" checked={marketing} onChange={event=>{setMarketing(event.target.checked);void save({action:'preferences',marketingEmail:event.target.checked});}} disabled={busy}/> Send me offers and event updates by email</label><p className="text-sm mt-3">Order and account messages are sent when needed to provide your service.</p></section>
    <section className="bg-white p-5 border rounded-xl"><h2 className="font-bold text-lg">Account deletion</h2><p className="text-sm my-3">Request deletion of your account and personal profile. Support will verify your request and retain transaction records where required.</p>{deletion?<p>Deletion request received.</p>:<button disabled={busy} className="text-ember" onClick={()=>save({action:'request-deletion'})}>Request account deletion</button>}</section>
  </div>;
}
