'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
type Ticket={order_id:string|null;id:string;category:string;message:string;status:string;staff_reply:string|null};
export default function SupportPanel({orderId}:{orderId?:string}){const[tickets,setTickets]=useState<Ticket[]>([]);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[signedOut,setSignedOut]=useState(false);
  const load=useCallback(async()=>{try{const res=await fetch('/api/support');if(res.status===401){setSignedOut(true);return;}const data=await res.json();if(!res.ok)throw new Error(data.error);setTickets(data.tickets);}catch(err){setMessage(err instanceof Error?err.message:'Could not load support.');}},[]);useEffect(()=>{void load();},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);try{const data=new FormData(form);const res=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(data),orderId})});const result=await res.json();if(!res.ok)throw new Error(result.error);form.reset();setMessage('Your request was sent. Replies will appear here.');await load();}catch(err){setMessage(err instanceof Error?err.message:'Could not submit.');}finally{setBusy(false);}}
  if(signedOut)return <Link href="/signin?next=/support" className="text-ember">Sign in to contact support</Link>;
  return <div className="space-y-5"><p role="status">{message}</p><form onSubmit={submit} className="space-y-3"><label className="block">Issue<select name="category" className="block border rounded p-2 w-full">{['damaged','incorrect','missing','undelivered','account','other'].map(category=><option key={category}>{category}</option>)}</select></label><label className="block">What happened?<textarea name="message" required minLength={10} maxLength={3000} className="block border rounded p-3 w-full" rows={4}/></label><button className="btn-brand px-5 py-3" disabled={busy}>Send request</button></form>{tickets.filter(ticket=>!orderId||ticket.order_id===orderId).map(ticket=><article className="rounded border p-4" key={ticket.id}><p className="font-bold">{ticket.category} · {ticket.status}</p><p className="mt-2 whitespace-pre-wrap">{ticket.message}</p>{ticket.staff_reply&&<p className="mt-3 bg-paper p-3 whitespace-pre-wrap">Support: {ticket.staff_reply}</p>}</article>)}</div>;
}
