/**
 * Responsive image manifest.
 *
 * The source PNGs in `public/` are 8–10MB each — unusable on a phone, and
 * `next.config.js` disables Next's own optimiser for Netlify. `public/img/`
 * holds pre-built WebP renditions at 640/1280/1920 instead (the whole set is
 * under 3MB), and each entry carries a 20px blurred placeholder inlined as a
 * data URI so a card never renders as an empty hole while the photo streams in.
 *
 * Generated by `npm run images` — do not edit by hand.
 */

export interface ImageAsset {
  width: number;
  height: number;
  blur: string;
}

export const WIDTHS = [640, 1280, 1920] as const;

export const IMAGES: Record<string, ImageAsset> = {
  'convivium': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JYgCdMoAluhesJ48HHmNot4iAAP7sSXCS2f7qgLVVsCxie+ci0gCrOu+1AkOMQZ6j+7617G7Z1ZpqdJO7auSw63iRWmJuG59u4rxf/s8tNm6FqJIHxp1L9lPM/vkEFsdVgRie9vn5rBNDhTUBAAAA' },
  'convivium2': { width: 3168, height: 1344, blur: 'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAAgAPu1iqU2ppaOiMAgBMB2JaACdMoR4GCT0qUad1gHQNgAA/qssmy0JWvOxApFvEcpWNxfPK0zZqlv5Z19ZFpAijm7FbbQ3I4kfJAC3zZ5Cw3iNa/r8r99x4IxHaQ3TlkahOmndSAAA' },
  'convivium3': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JbACdMoMYADMniwnjp2oXSnlAAM3ZgNwB8vs/cSbkIzvrTFzGIictWXfk0BVYGdFFyuGix1i2NJDTFlkWsos7i2u8tJ/fQGoqa25Ipdr79SJjfxyycDeB19fqDohISFB15kGAAAA=' },
  'homepage': { width: 3168, height: 1344, blur: 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoUAAgAPu1iqU2ppaQiMAgBMB2JZgCdLwABTtBYP0Iv5oxCAAD+7EQSvz5h5LxV8JTxPORz+a9gIHWiWpobWfCEFVL7D+3AxIpy1wOg+kCoIkQZNDxNBA0AAAA=' },
  'homepage2': { width: 3168, height: 1344, blur: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoUAAgAPu1iqU2ppaOiMAgBMB2JagCdMoR3ACmaM2Fe3rBZ3MAA/lvK//UmUT9+dO0EzggElBvzU2asylsm+MXTz+ONmjmnECB27zJBCNimwVtl802iOaRGWX+sFFl11DGMfvld1StDVBv8lmrr8AAA' },
  'the-spaces': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZgCdMoACjPNh9bzJq8/QAM11KNdoIwCAh2vghth0QdAtTEQVIJ1qwl8kfXr9aPfqUOHl1kqoeKGv13kwYYi93hBPMMj+rIOzf2SBWMaV0jIARGJnFH12Qmj8KHl0Hj1l/ygUXOg+FP6ox2n3KBAFXJHUAAAA' },
  'the-spaces2': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JQBOmUI8H0AVxYcBFe3u9aOFGjMAA/seB38ANGk0j6aGcwwR38TPrBbVGEycXhVj4t96+devImWNniROwyTPp9Cdw1QJFB7i7uzOMA+K+7nlX25r0OtgWEVdBMFWT1jpsfYEwW7mmAZfmwnQAAA==' },
  'the-spaces3': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZgCdMoR3ABshIIL9s+FAAPQFX8NWR7p31txro63pIKNLdbXWSVErqX5g0ddWDeRA0YuAURsup9ehOLMnUzV0aG3Sfn/W9pOPP739cPNSqay3ntrynzJ7uAA=' },
  'conv1': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JYgCdAYxEysQ3mYCLNgPQAADMS86xl/3WpH0t17Kv9HbPLiKKA+8nVgTfmvZT16ETmZATGDyJUXMxmBSQoKctEjnf3LQ3TwM2fcrd8krezNiSGf2aEdKSZ4A4T53RK4tj77htgzih3Iu6K/KAAA==' },
  'dealrooms': { width: 2816, height: 1536, blur: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwAAOHD1WzOilZVoyAAA/sXqUtuFQU9D3mK3xPDmBn2VYHO0tFm01G1OMwy0rLhVxPr3qzAxF9AJqwWjRxKKCWyDWbSzGkVRa/iHo1BrYLVhgN+ecygYiqepehHRl+NI9WB7862WmAAA' },
};

/** `/Homepage.png` and `homepage` both resolve to the same asset key. */
export function imageKey(src: string): string {
  return src
    .replace(/^\//, '')
    .replace(/\.[a-z0-9]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function getImage(src: string): ImageAsset | undefined {
  return IMAGES[imageKey(src)];
}

export function srcSetFor(src: string): string {
  const key = imageKey(src);
  const asset = IMAGES[key];
  if (!asset) return '';
  return WIDTHS.filter((w) => w <= asset.width)
    .map((w) => `/img/${key}-${w}.webp ${w}w`)
    .join(', ');
}
