'use client';
import { useState, type ReactNode } from 'react';
import { PERIODS, type PeriodKey } from '@/lib/accounting/statements';
import type { AnalyticsReport } from '@/lib/analytics/types';
import { formatNgn } from '@/lib/drinks/catalog';
import AnalyticsChart from './AnalyticsChart';
import { useDesk } from './useDesk';
import { DeskHeader, DeskPanel, DeskEmpty, deskField, deskButton } from './ui/DeskContent';
const number = (value: number) => new Intl.NumberFormat('en-NG').format(value);
const pct = (part: number, total: number) => total ? `${(part / total * 100).toFixed(1)}%` : '0.0%';
const words = (value: string) => value.replace(/[_:-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
type Pane = 'overview' | 'commerce' | 'api' | 'engagement';
function Stats({ items }: { items: { label: string; value: ReactNode; detail?: string }[] }) {
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(item => <div key={item.label} className="rounded-xl border border-obsidian/10 bg-white p-5"><p className="text-sm text-obsidian/60">{item.label}</p><p className="mt-2 text-2xl font-bold tabular-nums break-words">{item.value}</p>{item.detail && <p className="mt-2 text-xs text-obsidian/60">{item.detail}</p>}</div>)}</div>;
}
function Table({ title, columns, rows }: { title: string; columns: string[]; rows: ReactNode[][] }) {
  const [page, setPage] = useState(0); const pages = Math.max(1, Math.ceil(rows.length / 20)); const current = Math.min(page, pages - 1);
  if (!rows.length) return <DeskEmpty>No records in this period.</DeskEmpty>;
  return <div className="space-y-3"><div className="overflow-x-auto rounded-lg border border-obsidian/10"><table className="w-full min-w-[480px] text-sm"><caption className="sr-only">{title}</caption><thead className="bg-paper"><tr>{columns.map((column, index) => <th key={column} scope="col" className={`px-4 py-3 font-semibold ${index ? 'text-right' : 'text-left'}`}>{column}</th>)}</tr></thead><tbody>{rows.slice(current * 20, current * 20 + 20).map((row, i) => <tr key={i} className="border-t border-obsidian/10 hover:bg-paper/50">{row.map((cell, j) => <td key={j} className={`px-4 py-3 tabular-nums ${j ? 'text-right' : 'text-left'}`}>{cell}</td>)}</tr>)}</tbody></table></div>{pages > 1 && <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>{rows.length} rows · Page {current + 1} of {pages}</span><div className="flex gap-2"><button className={deskButton} disabled={!current} onClick={() => setPage(current - 1)}>Previous rows</button><button className={deskButton} disabled={current >= pages - 1} onClick={() => setPage(current + 1)}>Next rows</button></div></div>}</div>;
}
export default function AnalyticsDesk() {
  const [period, setPeriod] = useState<PeriodKey>('30d'); const [pane, setPane] = useState<Pane>('overview');
  const desk = useDesk<AnalyticsReport>(`/api/admin/analytics?period=${period}`); const report = desk.data;
  const [metric, setMetric] = useState<'revenue' | 'orders'>('revenue');
  return <div className="space-y-6"><DeskHeader {...desk} title="Analytics" description="Review commerce performance, recorded API usage, stock and customer engagement. Charts show values, and tables provide the exact figures behind them." />
    <div className="flex flex-wrap items-end justify-between gap-3"><label className="text-sm">Reporting period<select value={period} onChange={e => setPeriod(e.target.value as PeriodKey)} className={deskField}>{PERIODS.map(p => <option key={p.key} value={p.key}>{p.label}</option>)}</select></label><nav aria-label="Analytics views" className="flex flex-wrap gap-2">{(['overview', 'commerce', 'api', 'engagement'] as Pane[]).map(view => <button key={view} className={`${deskButton} ${pane === view ? 'bg-ember/10 text-ember border-ember/30' : 'bg-white'}`} aria-pressed={pane === view} onClick={() => setPane(view)}>{view === 'api' ? 'API usage' : words(view)}</button>)}</nav></div>
    {report && !desk.loading && <div key={report.period} className="space-y-6"><p className="text-sm text-obsidian/60">{report.range.label} · {new Date(report.range.from).toLocaleDateString('en-GB')} to {new Date(report.range.to).toLocaleDateString('en-GB')}</p>
      {(pane === 'overview' || pane === 'commerce') && <><Stats items={[{ label: 'Net order revenue', value: formatNgn(report.commerce.revenueNgn), detail: 'Collected order totals less refunds; includes delivery.' }, { label: 'Collected orders', value: number(report.commerce.orders), detail: 'Includes orders subsequently refunded.' }, { label: 'Average collected order', value: formatNgn(report.commerce.aovNgn), detail: 'Net revenue divided by collected orders.' }, { label: 'Refunds recorded', value: formatNgn(report.commerce.refundedNgn) }]} />
      <DeskPanel title="Commerce trend" description="Revenue and order counts grouped by order creation date in Lagos."><label className="block max-w-xs text-sm">Chart measure<select className={deskField} value={metric} onChange={e => setMetric(e.target.value as 'revenue' | 'orders')}><option value="revenue">Net revenue (NGN)</option><option value="orders">Collected orders</option></select></label><AnalyticsChart key={metric} title={metric === 'revenue' ? 'Net revenue' : 'Collected orders'} points={report.commerce.trend.map(row => ({ label: row.day, value: metric === 'revenue' ? row.revenueNgn : row.orders }))} format={metric === 'revenue' ? formatNgn : number} /><Table title="Daily commerce values" columns={['Day (Lagos)', 'Collected orders', 'Net revenue', 'Average order']} rows={[...report.commerce.trend].reverse().map(row => [row.day, number(row.orders), formatNgn(row.revenueNgn), formatNgn(row.orders ? Math.round(row.revenueNgn / row.orders) : 0)])} /></DeskPanel></>}
      {pane === 'commerce' && <><DeskPanel title="Orders by status" description="All orders created in the selected period, including unpaid and cancelled orders."><Table title="Orders by status" columns={['Status', 'Orders', 'Share of all orders']} rows={report.commerce.byStatus.map(row => [words(row.status), number(row.count), pct(row.count, report.commerce.byStatus.reduce((sum, r) => sum + r.count, 0))])} /></DeskPanel><DeskPanel title="Top products" description="Top 12 products by units on collected orders. Item totals are before order discounts, delivery fees and refunds."><Table title="Top products" columns={['Product / SKU', 'Units', 'Gross item sales']} rows={report.commerce.topSkus.map(row => [<span key={row.sku} className="block"><span className="font-semibold">{row.name}</span><span className="block text-xs text-obsidian/60">{row.sku}</span></span>, number(row.qty), formatNgn(row.revenueNgn)])} /></DeskPanel></>}
      {(pane === 'overview' || pane === 'api') && <><Stats items={[{ label: 'Recorded API requests', value: report.api.configured && !report.api.error ? number(report.api.totalHits) : 'Unavailable', detail: 'Rate-limited routes only; not website visitors.' }, { label: 'Blocked requests', value: report.api.configured && !report.api.error ? number(report.api.totalBlocked) : 'Unavailable' }, { label: 'Block rate', value: report.api.configured && !report.api.error ? pct(report.api.totalBlocked, report.api.totalHits) : 'Unavailable' }, { label: 'Tracked routes', value: report.api.configured && !report.api.error ? number(report.api.routes.length) : 'Unavailable' }]} /><DeskPanel title="API traffic" description="Daily rate-limit counters are retained for 45 days. This is request activity, not Google Analytics visitor or session data.">{!report.api.configured || report.api.error ? <DeskEmpty>{report.api.error || 'API counters are not configured. Enable Redis to record request activity.'}</DeskEmpty> : <><AnalyticsChart title="API requests" points={report.api.days.map(row => ({ label: row.day, value: row.hits }))} format={number} /><Table title="Daily API values" columns={['Day (Lagos)', 'Requests', 'Blocked', 'Block rate']} rows={[...report.api.days].reverse().map(row => [row.day, number(row.hits), number(row.blocked), pct(row.blocked, row.hits)])} /></>}</DeskPanel></>}
      {pane === 'api' && report.api.configured && !report.api.error && <DeskPanel title="Usage by route"><Table title="API route usage" columns={['Route', 'Requests', 'Blocked', 'Block rate']} rows={report.api.routes.map(row => [row.route, number(row.hits), number(row.blocked), pct(row.blocked, row.hits)])} /></DeskPanel>}
      {(pane === 'overview' || pane === 'engagement') && <><Stats items={[{ label: 'Loyalty members', value: number(report.loyalty.members), detail: 'Current total, independent of period.' }, { label: 'Outstanding points', value: number(report.loyalty.pointsOutstanding), detail: `${formatNgn(report.loyalty.pointsLiabilityNgn)} current reward liability` }, { label: 'Low stock products', value: number(report.inventory.lowStock), detail: 'Current inventory; not a historical snapshot.' }, { label: 'Active stock units', value: number(report.inventory.onHandUnits), detail: `${number(report.inventory.activeSkus)} active products` }]} /></>}
      {pane === 'engagement' && <DeskPanel title="Customer engagement" description="Activity created during the selected reporting period."><Table title="Customer engagement values" columns={['Activity', 'Count']} rows={[[ 'Trivia entries', number(report.engagement.triviaEntries)], ['Trivia wins', number(report.engagement.triviaWins)], ['Brand enquiries', number(report.engagement.brandEnquiries)], ['Restock alerts', number(report.engagement.restockAlerts)], ['Product reviews', number(report.engagement.productReviews)], ['Loyalty points awarded', number(report.loyalty.pointsAwardedInPeriod)]]} /></DeskPanel>}
      {pane === 'overview' && <DeskPanel title="Configured integrations" description="Configuration presence does not confirm that a provider is online."><Table title="Integration configuration" columns={['Integration', 'Configuration']} rows={Object.entries(report.systems).map(([key, configured]) => [words(key), configured ? 'Configured' : 'Not configured'])} /></DeskPanel>}
    </div>}
  </div>;
}
