'use client';
import { useState, type FormEvent } from 'react';
import { LAUNCH_CITIES } from '@/lib/delivery/policy';
import { formatNgn } from '@/lib/drinks/catalog';
import { useDesk } from './useDesk';
import { DeskHeader, DeskPanel, DeskEmpty, DeskStats, deskField, deskButton } from './ui/DeskContent';
type Zone = { id: string; city: string; name: string; fee_ngn: number; estimate: string; active: boolean };
type Provider = { id: string; name: string; contact: string; active: boolean };
export default function DeliveryDesk() {
  const desk = useDesk<{ zones: Zone[]; providers: Provider[] }>('/api/admin/delivery');
  const [zone, setZone] = useState<Zone | null>(null); const [provider, setProvider] = useState<Provider | null>(null);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = new FormData(form);
    if (await desk.save({ ...Object.fromEntries(values), active: values.get('active') === 'on' }, 'Delivery settings saved.')) { setZone(null); setProvider(null); form.reset(); }
  }
  return <div className="space-y-6"><DeskHeader {...desk} title="Delivery settings" description="Set the areas your supplier serves, with accurate delivery fees and estimates. Customers see only enabled zones at checkout. Couriers are delivery contacts, separate from your supplier." />
    <button type="button" disabled={!desk.data || desk.loading || desk.busy} onClick={() => { setProvider(null); document.getElementById('courier-providers')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }} className="btn-brand inline-flex rounded-lg px-4 py-3 disabled:opacity-40">Add courier</button>
    {desk.data && <><DeskStats items={[{ label: 'Enabled zones', value: desk.data.zones.filter(z => z.active).length }, { label: 'Cities served', value: new Set(desk.data.zones.filter(z => z.active).map(z => z.city)).size }, { label: 'Disabled zones', value: desk.data.zones.filter(z => !z.active).length }, { label: 'Enabled couriers', value: desk.data.providers.filter(p => p.active).length }]} />
    <div id="courier-providers" className="scroll-mt-28"><DeskPanel title="Courier providers" description="Add another courier using the form below. Keep booking contacts here. Staff book the courier and record tracking against each order."><form key={provider?.id || 'new-provider'} onSubmit={save} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="kind" value="provider" />{provider && <input type="hidden" name="id" value={provider.id} />}<label className="text-sm">Provider name<input className={deskField} name="name" defaultValue={provider?.name} required maxLength={100} /></label><label className="text-sm">Provider contact<input className={deskField} name="contact" defaultValue={provider?.contact} placeholder="Phone or booking contact" maxLength={200} /></label><label className="flex gap-2 items-center text-sm"><input name="active" type="checkbox" defaultChecked={provider?.active ?? true} /> Enable provider</label><div className="flex gap-2"><button disabled={desk.busy || desk.loading} className="btn-brand rounded-lg px-4 py-2 disabled:opacity-40">{provider ? 'Save courier changes' : 'Add courier provider'}</button>{provider && <button type="button" className={deskButton} onClick={() => setProvider(null)}>Cancel edit</button>}</div></form>
    {!desk.data.providers.length && <DeskEmpty>No courier providers added. Add a booking contact for your delivery team.</DeskEmpty>}{desk.data.providers.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-3 border-t pt-3"><div><p className="font-semibold">{row.name} · {row.active ? 'Enabled' : 'Disabled'}</p><p className="text-sm text-obsidian/60">{row.contact || 'No booking contact recorded'}</p></div><div className="flex gap-2"><button className={deskButton} disabled={desk.busy || desk.loading} onClick={() => setProvider(row)}>Edit provider</button><button className={deskButton} disabled={desk.busy || desk.loading} onClick={() => void desk.save({ kind: 'provider', id: row.id, name: row.name, contact: row.contact, active: !row.active }, 'Courier availability updated.')}>{row.active ? 'Disable' : 'Enable'}</button></div></div>)}</DeskPanel></div>
    <DeskPanel title="Delivery zones" description="Add only areas your supplier can fulfill. Editing a zone changes its fee and estimate for future checkout quotes."><form key={zone?.id || 'new-zone'} onSubmit={save} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><input type="hidden" name="kind" value="zone" />{zone && <input type="hidden" name="id" value={zone.id} />}<label className="text-sm">City<select name="city" className={deskField} defaultValue={zone?.city || LAUNCH_CITIES[0]}>{LAUNCH_CITIES.map(city => <option key={city}>{city}</option>)}</select></label><label className="text-sm">Zone name<input className={deskField} name="name" defaultValue={zone?.name} placeholder="e.g. Victoria Island" required maxLength={100} /></label><label className="text-sm">Delivery fee in naira<input className={deskField} name="feeNgn" defaultValue={zone ? Number(zone.fee_ngn) : undefined} type="number" min={0} step={1} required /></label><label className="text-sm">Delivery estimate<input className={deskField} name="estimate" defaultValue={zone?.estimate} placeholder="e.g. Within 2–4 hours" required maxLength={200} /></label><label className="flex gap-2 items-center text-sm"><input name="active" type="checkbox" defaultChecked={zone?.active || false} /> Enable at checkout</label><div className="flex gap-2 items-end"><button disabled={desk.busy || desk.loading} className="btn-brand rounded-lg px-4 py-2 disabled:opacity-40">{zone ? 'Save changes' : 'Add zone'}</button>{zone && <button type="button" className={deskButton} onClick={() => setZone(null)}>Cancel edit</button>}</div></form>
    {!desk.data.zones.length && <DeskEmpty>No zones configured. Checkout remains unavailable until a zone is enabled.</DeskEmpty>}{desk.data.zones.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-3 border-t pt-3"><div><p className="font-semibold">{row.name} · {row.city}</p><p className="text-sm text-obsidian/60">{formatNgn(Number(row.fee_ngn))} · {row.estimate} · {row.active ? 'Enabled' : 'Disabled'}</p></div><div className="flex gap-2"><button className={deskButton} disabled={desk.busy || desk.loading} onClick={() => setZone(row)}>Edit zone</button><button className={deskButton} disabled={desk.busy || desk.loading} onClick={() => void desk.save({ kind: 'zone', id: row.id, city: row.city, name: row.name, feeNgn: Number(row.fee_ngn), estimate: row.estimate, active: !row.active }, 'Zone availability updated.')}>{row.active ? 'Disable' : 'Enable'}</button></div></div>)}</DeskPanel></>}
  </div>;
}
