'use client';
import { useState } from 'react';
import { formatNgn } from '@/lib/drinks/catalog';
import { hasAdminPermission, type StaffRole } from '@/lib/admin-permissions';
import { useDesk } from './useDesk';
import { useDialogs } from './ui/DialogProvider';
import { DeskHeader, DeskPanel, DeskEmpty, DeskStats, deskField, deskButton } from './ui/DeskContent';
type Row = { id: string; venue_name?: string; email?: string; approval_status?: string; status?: string; total_ngn?: number; reward_name?: string; code?: string; tracking_reference?: string };
type Data = { outlets: Row[]; wholesale: Row[]; rewards: Row[] };
export default function OperationsDesk({ role = 'owner' }: { role?: StaffRole }) {
  const desk = useDesk<Data>('/api/admin/operations'); const { confirm } = useDialogs();
  const [references, setReferences] = useState<Record<string, string>>({}); const [showAll, setShowAll] = useState(false);
  const canOperate = hasAdminPermission(role, 'operations'); const canFinance = hasAdminPermission(role, 'finance'); const canApprove = hasAdminPermission(role, 'owner');
  async function update(kind: string, row: Row, status: string) {
    const consequential = ['refunded', 'cancelled', 'suspended', 'fulfilled'].includes(status);
    if (consequential && !await confirm({ title: status === 'refunded' ? 'Confirm full bank refund?' : `Confirm ${status.replace('_', ' ')}?`, message: status === 'refunded' ? `Confirm ${formatNgn(Number(row.total_ngn))} was returned through the bank. This records a completed refund.` : status === 'cancelled' && kind === 'reward' ? 'The reward will be cancelled and the customer’s points returned.' : 'This updates the selected record and is recorded in the audit history.', confirmLabel: 'Confirm update', tone: status === 'fulfilled' ? 'default' : 'danger' })) return;
    await desk.save({ kind, id: row.id, status, reference: references[row.id] || '', note: references[row.id] || '', ...(status === 'refunded' ? { amountNgn: Number(row.total_ngn) } : {}) }, 'Record updated.');
  }
  const action = (kind: string, row: Row, status: string, label: string, needsReference = false) => <button key={status} className={deskButton} disabled={desk.busy || desk.loading || (needsReference && !references[row.id]?.trim())} onClick={() => void update(kind, row, status)}>{label}</button>;
  const note = (row: Row, label: string) => <label className="block text-sm">{label}<input className={deskField} value={references[row.id] || ''} onChange={e => setReferences(r => ({ ...r, [row.id]: e.target.value }))} maxLength={120} /></label>;
  const outlets = desk.data?.outlets.filter(row => showAll || row.approval_status === 'pending') || [];
  const wholesale = desk.data?.wholesale.filter(row => showAll || ['awaiting_payment', 'paid', 'packed', 'dispatched'].includes(row.status || '')) || [];
  const rewards = desk.data?.rewards.filter(row => showAll || row.status === 'issued') || [];
  return <div className="space-y-6"><DeskHeader {...desk} title="Partners & rewards" description="Approve partner venues, follow wholesale orders from payment to dispatch, and record reward fulfillment. Actions follow your staff permissions." />
    {desk.data && <><DeskStats items={[{ label: 'Partners awaiting approval', value: desk.data.outlets.filter(o => o.approval_status === 'pending').length }, { label: 'Wholesale awaiting payment', value: desk.data.wholesale.filter(o => o.status === 'awaiting_payment').length }, { label: 'Wholesale to pack or dispatch', value: desk.data.wholesale.filter(o => ['paid', 'packed'].includes(o.status || '')).length }, { label: 'Rewards to fulfill', value: desk.data.rewards.filter(o => o.status === 'issued').length }]} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showAll} onChange={e => setShowAll(e.target.checked)} /> Include completed and inactive records</label>
    <DeskPanel title="Partner approvals" description="Approve verified venues before they place wholesale orders. Suspending an outlet blocks new purchases.">{!outlets.length && <DeskEmpty>No partner approvals in this view.</DeskEmpty>}{outlets.map(row => <article key={row.id} className="space-y-3 border-t pt-4"><p className="font-semibold">{row.venue_name} · {row.approval_status}</p><p className="text-sm">{row.email}</p>{canApprove && <div className="flex flex-wrap gap-2">{row.approval_status !== 'approved' && action('outlet', row, 'approved', 'Approve partner')}{row.approval_status !== 'suspended' && action('outlet', row, 'suspended', 'Suspend partner')}</div>}</article>)}</DeskPanel>
    <DeskPanel title="Wholesale fulfillment" description="Confirm payment against bank records, pack the order, then record dispatch. Partners confirm receipt in their portal. Returned goods require a physical stock count.">{!wholesale.length && <DeskEmpty>No wholesale orders in this view.</DeskEmpty>}{wholesale.map(row => <article key={row.id} className="space-y-3 border-t pt-4"><p className="font-semibold">{row.venue_name} · {formatNgn(Number(row.total_ngn))} · {row.status}</p><p className="text-xs text-obsidian/60 break-all">Order {row.id}{row.tracking_reference ? ` · Dispatch ${row.tracking_reference}` : ''}</p>{((canFinance && ['awaiting_payment', 'paid', 'packed', 'dispatched', 'delivered'].includes(row.status || '')) || (canOperate && row.status === 'packed')) && note(row, row.status === 'awaiting_payment' ? 'Bank payment reference' : row.status === 'packed' ? 'Dispatch reference or bank refund reference' : 'Bank refund reference')}<div className="flex flex-wrap gap-2">{row.status === 'awaiting_payment' && <>{canFinance && action('wholesale', row, 'paid', 'Confirm payment', true)}{canOperate && action('wholesale', row, 'cancelled', 'Cancel order')}</>}{row.status === 'paid' && canOperate && action('wholesale', row, 'packed', 'Mark packed')}{row.status === 'packed' && canOperate && action('wholesale', row, 'dispatched', 'Record dispatch', true)}{row.status === 'dispatched' && <p className="text-sm text-obsidian/60">Awaiting the partner’s receipt confirmation.</p>}{canFinance && ['paid', 'packed', 'dispatched', 'delivered'].includes(row.status || '') && action('wholesale', row, 'refunded', 'Confirm full bank refund', true)}</div></article>)}</DeskPanel>
    <DeskPanel title="Reward fulfillment" description="Confirm fulfillment after the customer receives the reward. Cancelling an issued reward returns its points.">{!rewards.length && <DeskEmpty>No rewards to fulfill in this view.</DeskEmpty>}{rewards.map(row => <article key={row.id} className="space-y-3 border-t pt-4"><p className="font-semibold">{row.reward_name} · {row.status}</p><p className="text-sm">{row.code} · {row.email || 'Customer email unavailable'}</p>{row.status === 'issued' && canOperate && <>{note(row, 'Fulfillment or cancellation note')}<div className="flex flex-wrap gap-2">{action('reward', row, 'fulfilled', 'Confirm fulfilled', true)}{action('reward', row, 'cancelled', 'Cancel and return points', true)}</div></>}</article>)}</DeskPanel></>}
  </div>;
}
