'use client';
import { useState } from 'react';
import type { ReadinessCheck } from '@/lib/launch-readiness';
import { useDesk } from './useDesk';
import { DeskHeader, DeskPanel, DeskEmpty, DeskStats, deskButton } from './ui/DeskContent';
type Data = { targetDate: string; ready: boolean; checks: ReadinessCheck[] };
const destination = (name: string) => /delivery|courier/i.test(name) ? 'delivery' : /supplier/i.test(name) ? 'suppliers' : /stock/i.test(name) ? 'drinks' : /notification|payment/i.test(name) ? 'refunds' : /event/i.test(name) ? 'content' : '';
export default function ReadinessDesk() {
  const desk = useDesk<Data>('/api/admin/readiness'); const [requiredOnly, setRequiredOnly] = useState(true);
  const manual = ['Place a test order and confirm payment, packing, courier handoff and receipt.', 'Verify a refund and confirm customer notifications are delivered.', 'Check checkout and the customer account on mobile and desktop.', 'Verify that a database backup can be restored and staff know how to handle support requests.'];
  return <div className="space-y-6"><DeskHeader {...desk} title="Launch readiness" description="Review configuration and operational checks for your supplier and enabled delivery areas. Resolve required items, then refresh to check again." />
    {desk.data && <><p className="text-sm text-obsidian/60">Launch target: {new Date(`${desk.data.targetDate}T12:00:00Z`).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })}</p><DeskStats items={[{ label: 'Checks passed', value: desk.data.checks.filter(c => c.ok).length }, { label: 'Items requiring attention', value: desk.data.checks.filter(c => !c.ok).length }, { label: 'Total automated checks', value: desk.data.checks.length }]} /><p role="status" className={`rounded-lg p-4 font-semibold ${desk.data.ready ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-900'}`}>{desk.data.ready ? 'Automated checks passed. Complete the operational rehearsals below before launch.' : 'Launch requirements remain. Review the required items below.'}</p>
    <DeskPanel title="Automated checks"><label className="flex gap-2 text-sm"><input type="checkbox" checked={requiredOnly} onChange={e => setRequiredOnly(e.target.checked)} /> Show required items only</label>{!desk.data.checks.filter(c => !requiredOnly || !c.ok).length && <DeskEmpty>No outstanding automated requirements.</DeskEmpty>}{desk.data.checks.filter(c => !requiredOnly || !c.ok).map(check => <article key={check.name} className="space-y-2 border-t pt-4"><p className={`font-semibold ${check.ok ? 'text-emerald-700' : 'text-ember'}`}>{check.ok ? 'Passed' : 'Required'} · {check.name}</p><p className="text-sm text-obsidian/65 break-words">{check.detail}</p>{!check.ok && destination(check.name) && <a className={`${deskButton} inline-block`} href={`/admin#${destination(check.name)}`}>Open {destination(check.name) === 'suppliers' ? 'supplier' : destination(check.name)}</a>}</article>)}</DeskPanel></>}
    <DeskPanel title="Operational rehearsals" description="These checks require real verification and are not marked complete by the automated checks."><ol className="list-decimal pl-5 space-y-3 text-sm">{manual.map(item => <li key={item}>{item}</li>)}</ol></DeskPanel>
  </div>;
}
