'use client';
import { useState } from 'react';
import { formatNgn } from '@/lib/drinks/catalog';
import { useDesk } from './useDesk';
import { useDialogs } from './ui/DialogProvider';
import { DeskHeader, DeskPanel, DeskEmpty, DeskStats, deskField, deskButton } from './ui/DeskContent';
type Refund = { id: string; order_id: string; amount_ngn: number; status: string; provider: string; provider_reference: string | null; reason: string | null };
type Data = { refunds: Refund[]; jobs: { id: string; kind: string; status: string; attempts: number; last_error: string | null }[]; exceptions: { transaction_id: string; order_id: string; exception: string }[]; overdue: { id: string; payment_ref: string; payment_provider: string }[] };
export default function RefundsDesk() {
  const desk = useDesk<Data>('/api/admin/refunds'); const { confirm } = useDialogs();
  const [references, setReferences] = useState<Record<string, string>>({}); const [filter, setFilter] = useState('pending');
  const reference = (key: string, label: string, fallback = '') => <label className="block text-sm">{label}<input className={deskField} value={references[key] ?? fallback} onChange={e => setReferences(r => ({ ...r, [key]: e.target.value }))} maxLength={120} /></label>;
  return <div className="space-y-6"><DeskHeader {...desk} title="Refunds & exceptions" description="Verify refunds against payment records, reconcile exceptional payments and retry failed customer notifications. Confirm bank refunds only after funds have actually been returned." />
    {desk.data && <><DeskStats items={[{ label: 'Refunds awaiting verification', value: desk.data.refunds.filter(r => ['pending', 'requested'].includes(r.status)).length }, { label: 'Payment exceptions', value: desk.data.exceptions.length }, { label: 'Overdue payment holds', value: desk.data.overdue.length }, { label: 'Failed notifications', value: desk.data.jobs.filter(j => j.status === 'failed').length }]} />
    <DeskPanel title="Refund requests"><label className="block text-sm">Show refunds<select className={deskField} value={filter} onChange={e => setFilter(e.target.value)}><option value="pending">Awaiting verification</option><option value="all">All recent refunds</option></select></label>
    {!desk.data.refunds.filter(r => filter === 'all' || ['pending', 'requested'].includes(r.status)).length && <DeskEmpty>No refunds in this view. Refund requests made from Orders will appear here.</DeskEmpty>}
    {desk.data.refunds.filter(r => filter === 'all' || ['pending', 'requested'].includes(r.status)).map(row => <article key={row.id} className="space-y-3 border-t pt-4"><p className="font-semibold">{formatNgn(Number(row.amount_ngn))} · {row.provider} · {row.status}</p><a href="/admin#orders" className="text-sm text-ember break-all">Order {row.order_id}</a><p className="text-sm">{row.reason || 'No reason recorded.'}</p>{['pending', 'requested'].includes(row.status) && <>{reference(row.id, row.provider === 'flutterwave' ? 'Provider refund ID' : 'Bank return reference', row.provider_reference || '')}<button className={deskButton} disabled={desk.busy || desk.loading || !(references[row.id] ?? row.provider_reference ?? '').trim()} onClick={async () => { if (row.provider !== 'flutterwave' && !await confirm({ title: 'Confirm bank refund?', message: `Confirm that ${formatNgn(Number(row.amount_ngn))} has been returned for this order.`, confirmLabel: 'Confirm returned funds' })) return; await desk.save({ id: row.id, action: 'reconcile', reference: references[row.id] ?? row.provider_reference }, 'Refund completion verified.'); }}>Verify completion</button></>}</article>)}</DeskPanel>
    <DeskPanel title="Payment exceptions" description="Check each transaction in the payment provider or bank records. Record the external reconciliation reference before clearing the exception.">{!desk.data.exceptions.length && <DeskEmpty>No unresolved payment exceptions.</DeskEmpty>}{desk.data.exceptions.map(row => <article key={row.transaction_id} className="space-y-3 border-t pt-4"><p className="text-sm break-all">Order {row.order_id} · Transaction {row.transaction_id}</p><p className="text-sm text-ember">{row.exception}</p>{reference(row.transaction_id, 'External reconciliation reference')}<button className={deskButton} disabled={desk.busy || desk.loading || !references[row.transaction_id]?.trim()} onClick={async () => { if (!await confirm({ title: 'Clear payment exception?', message: 'Confirm this transaction was reconciled externally. The reference will be saved in the audit history.', confirmLabel: 'Record reconciliation' })) return; await desk.save({ id: row.order_id, transactionId: row.transaction_id, action: 'resolve-exception', reference: references[row.transaction_id] }, 'Payment exception reconciled.'); }}>Record external reconciliation</button></article>)}</DeskPanel>
    <DeskPanel title="Overdue payment holds" description="Check these references in the provider dashboard and review the order. Unconfirmed payments must not release stock during a provider outage.">{!desk.data.overdue.length && <DeskEmpty>No overdue payment holds.</DeskEmpty>}{desk.data.overdue.map(row => <p key={row.id} className="border-t pt-3 text-sm break-all"><a href="/admin#orders" className="text-ember">Order {row.id}</a> · {row.payment_provider || 'Provider not recorded'} · {row.payment_ref || 'Reference not recorded'}</p>)}</DeskPanel>
    <DeskPanel title="Notification queue" description="Failed messages can be requeued. The notification worker sends them on its next run.">{!desk.data.jobs.length && <DeskEmpty>No pending or failed notifications.</DeskEmpty>}{desk.data.jobs.map(job => <div key={job.id} className="flex flex-wrap justify-between gap-3 border-t pt-3"><div><p className="text-sm font-semibold">{job.kind} · {job.status} · {job.attempts} attempts</p>{job.last_error && <p className="text-sm text-ember break-words">{job.last_error}</p>}</div>{job.status === 'failed' && <button className={deskButton} disabled={desk.busy || desk.loading} onClick={() => void desk.save({ id: job.id, action: 'retry-notification' }, 'Notification requeued for delivery.')}>Retry notification</button>}</div>)}</DeskPanel></>}
  </div>;
}
