'use client';
import {useCallback,useEffect,useState} from 'react';
import {formatNgn} from '@/lib/drinks/catalog';
type Refund={id:string;order_id:string;amount_ngn:number;status:string;provider:string;provider_reference:string|null;reason:string|null};
type Job={id:string;status:string;attempts:number;last_error:string|null};
export default function RefundsDesk(){const[refunds,setRefunds]=useState<Refund[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[exceptions,setExceptions]=useState<{transaction_id:string;order_id:string;exception:string}[]>([]);const[overdue,setOverdue]=useState<{id:string;payment_ref:string;payment_provider:string}[]>([]);const[msg,setMsg]=useState('');const[reference,setReference]=useState('');const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const res=await fetch('/api/admin/refunds');const data=await res.json();if(!res.ok)throw new Error(data.error);setRefunds(data.refunds);setJobs(data.jobs);setExceptions(data.exceptions);setOverdue(data.overdue || []);}catch(err){setMsg(err instanceof Error?err.message:'Could not load finance queue.');}},[]);useEffect(()=>{void load();},[load]);
  async function act(id:string,action:string,transactionId?:string){setBusy(true);try{const res=await fetch('/api/admin/refunds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,reference,transactionId})});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();setMsg('Updated.');}catch(err){setMsg(err instanceof Error?err.message:'Could not update.');}finally{setBusy(false);}}
  return <div className="space-y-6"><p role="status">{msg}</p><label className="block">Refund ID or bank return reference<input className="border rounded p-2 ml-3" value={reference} onChange={e=>setReference(e.target.value)}/></label><section className="rounded-xl bg-white p-5"><h2 className="font-bold text-lg">Refund requests</h2>{refunds.length===0&&<p className="mt-3">No refund requests.</p>}{refunds.map(refund=><div className="border-t py-3 flex flex-wrap justify-between gap-3" key={refund.id}><span>{refund.order_id.slice(0,8)} · {formatNgn(Number(refund.amount_ngn))} · {refund.provider} · {refund.status}<span className="block text-sm">{refund.reason}</span></span>{['pending','requested'].includes(refund.status)&&<button disabled={busy} onClick={()=>act(refund.id,'reconcile')}>Verify completion</button>}</div>)}</section><section className="rounded-xl bg-white p-5"><h2 className="font-bold text-lg">Payment exceptions</h2>{exceptions.map(row=><p className="border-t py-3" key={row.transaction_id}>Order {row.order_id} · transaction {row.transaction_id} · {row.exception} <button disabled={busy || !reference.trim()} onClick={()=>act(row.order_id,'resolve-exception',row.transaction_id)}>Record external reconciliation</button></p>)}</section><section className="rounded-xl bg-white p-5"><h2 className="font-bold text-lg">Overdue payment holds</h2><p>Verify these references in the provider dashboard. A provider outage must not release stock for an unconfirmed payment.</p>{overdue.map(row=><p key={row.id} className="py-2 border-t">{row.id} · {row.payment_provider} · {row.payment_ref}</p>)}</section><section className="rounded-xl bg-white p-5"><h2 className="font-bold text-lg">Notification queue</h2>{jobs.map(job=><div className="border-t py-3 flex justify-between gap-3" key={job.id}><span>{job.status} · {job.attempts} attempts · {job.last_error}</span>{job.status==='failed'&&<button disabled={busy} onClick={()=>act(job.id,'retry-notification')}>Retry</button>}</div>)}</section></div>;
}
