'use client';
import { useState } from 'react';
import { STAFF_ROLES, type StaffRole } from '@/lib/admin-permissions';
import { useDialogs } from './ui/DialogProvider';
import { useDesk } from './useDesk';
import { DeskHeader, DeskPanel, DeskEmpty, DeskStats, deskField, deskButton } from './ui/DeskContent';
type Staff = { email: string; role: StaffRole; active: boolean };
type Audit = { id: string; actor: string; action: string; subject: string; created_at: string };
const descriptions: Record<StaffRole, string> = { owner: 'Full desk access, staff access and launch checks.', operations: 'Orders, stock, delivery, support and reward fulfillment.', finance: 'Orders, accounting, refunds and payment reconciliation.', content: 'Events, venues and trivia.' };
export default function StaffDesk() {
  const desk = useDesk<{ staff: Staff[]; audit: Audit[] }>('/api/admin/staff');
  const { confirm } = useDialogs(); const [search, setSearch] = useState('');
  return <div className="space-y-6"><DeskHeader {...desk} title="Staff & audit" description="Give staff access through their own Convivia24 accounts and review recorded admin activity. Owner allowlist accounts are managed in deployment settings." />
    <DeskPanel title="Staff roles"><div className="grid gap-3 sm:grid-cols-2">{STAFF_ROLES.map(role => <div key={role} className="rounded-lg bg-paper p-3"><p className="font-semibold capitalize">{role}</p><p className="text-sm text-obsidian/60">{descriptions[role]}</p></div>)}</div></DeskPanel>
    {desk.data && <><DeskStats items={[{ label: 'Active staff', value: desk.data.staff.filter(s => s.active).length }, { label: 'Revoked access', value: desk.data.staff.filter(s => !s.active).length }, { label: 'Recent audit records', value: desk.data.audit.length }]} />
    <DeskPanel title="Grant staff access" description="The email must match the account the staff member uses to sign in."><form className="grid gap-3 sm:grid-cols-3" onSubmit={async event => {
      event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const role = String(values.get('role'));
      if (role === 'owner' && !await confirm({ title: 'Grant owner access?', message: 'This account will have full access, including staff permissions and finance.', confirmLabel: 'Grant owner access' })) return;
      if (await desk.save({ email: values.get('email'), role, active: true }, 'Staff access granted.')) form.reset();
    }}><label className="text-sm">Staff email<input className={deskField} name="email" type="email" required placeholder="name@example.com" /></label><label className="text-sm">Role<select name="role" className={deskField} defaultValue="operations">{STAFF_ROLES.map(role => <option key={role} value={role}>{role}</option>)}</select></label><button className="btn-brand rounded-lg px-4 py-2 self-end disabled:opacity-40" disabled={desk.busy || desk.loading}>Grant access</button></form></DeskPanel>
    <DeskPanel title="Staff accounts">{!desk.data.staff.length && <DeskEmpty>No staff accounts added. Your configured owner accounts still have access.</DeskEmpty>}{desk.data.staff.map(person => <form key={`${person.email}-${person.role}-${person.active}`} className="grid items-end gap-3 border-t pt-3 sm:grid-cols-3" onSubmit={async event => { event.preventDefault(); const values = new FormData(event.currentTarget); if (values.get('role') === 'owner' && !await confirm({ title: 'Grant owner access?', message: `Give ${person.email} full desk access?` })) return; await desk.save({ ...person, role: values.get('role') }, 'Staff role updated.'); }}><div><p className="text-sm font-semibold break-all">{person.email}</p><p className="text-xs text-obsidian/60">{person.active ? 'Active' : 'Access revoked'}</p><label className="block text-sm mt-2">Role for {person.email}<select name="role" defaultValue={person.role} className={deskField}>{STAFF_ROLES.map(role => <option key={role}>{role}</option>)}</select></label></div><button className={deskButton} disabled={desk.busy || desk.loading}>Save role</button><button type="button" className={deskButton} disabled={desk.busy || desk.loading} onClick={async () => { if (person.active && !await confirm({ title: 'Revoke staff access?', message: `${person.email} will lose staff access. Owner allowlist access is managed separately.`, tone: 'danger', confirmLabel: 'Revoke access' })) return; await desk.save({ ...person, active: !person.active }, 'Staff access updated.'); }}>{person.active ? 'Revoke access' : 'Enable access'}</button></form>)}</DeskPanel>
    <DeskPanel title="Recent audit history" description="The latest 100 recorded admin actions. Search by actor, action or record."><label className="block text-sm">Search audit history<input className={deskField} value={search} onChange={e => setSearch(e.target.value)} /></label>{!desk.data.audit.filter(row => `${row.actor} ${row.action} ${row.subject}`.toLowerCase().includes(search.toLowerCase())).length && <DeskEmpty>No matching audit records.</DeskEmpty>}{desk.data.audit.filter(row => `${row.actor} ${row.action} ${row.subject}`.toLowerCase().includes(search.toLowerCase())).map(row => <div key={row.id} className="border-t pt-3 text-sm break-words"><p className="font-semibold">{row.action}</p><p>{row.actor} · {row.subject}</p><p className="text-xs text-obsidian/60">{new Date(row.created_at).toLocaleString()}</p></div>)}</DeskPanel></>}
  </div>;
}
