/**
 * Builds the responsive WebP renditions in `public/img/` and rewrites
 * `lib/images.ts`.
 *
 * The source photography is 8–10MB per PNG and `next.config.js` disables Next's
 * own optimiser (Netlify), so nothing shrinks these but this script. Run it
 * after adding or replacing a PNG in `public/`:
 *
 *     npm run images
 */

import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'public');
const OUT = path.join(SRC, 'img');
const WIDTHS = [640, 1280, 1920];

/** Logos and icons are already small and must not be re-encoded. */
const SKIP = /^(logo2|convivia24|icon-\d+|apple-icon)\.png$/i;

const key = (name) =>
  name
    .replace(/\.[a-z0-9]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

fs.mkdirSync(OUT, { recursive: true });

const files = fs.readdirSync(SRC).filter((f) => /\.png$/i.test(f) && !SKIP.test(f));
const entries = [];

for (const file of files) {
  const slug = key(file);
  const source = path.join(SRC, file);
  const meta = await sharp(source).metadata();

  for (const width of WIDTHS) {
    if (width > meta.width) continue;
    await sharp(source)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 74, effort: 6 })
      .toFile(path.join(OUT, `${slug}-${width}.webp`));
  }

  const blur = await sharp(source).resize({ width: 20 }).webp({ quality: 40 }).toBuffer();
  entries.push({ slug, width: meta.width, height: meta.height, blur: `data:image/webp;base64,${blur.toString('base64')}` });
  console.log(`${file} → ${slug} (${meta.width}×${meta.height})`);
}

const body = entries
  .map((e) => `  '${e.slug}': { width: ${e.width}, height: ${e.height}, blur: '${e.blur}' }`)
  .join(',\n');

const manifest = `/**
 * Responsive image manifest.
 *
 * The source PNGs in \`public/\` are 8–10MB each — unusable on a phone, and
 * \`next.config.js\` disables Next's own optimiser for Netlify. \`public/img/\`
 * holds pre-built WebP renditions at 640/1280/1920 instead (the whole set is
 * under 3MB), and each entry carries a 20px blurred placeholder inlined as a
 * data URI so a card never renders as an empty hole while the photo streams in.
 *
 * Generated by \`npm run images\` — do not edit by hand.
 */

export interface ImageAsset {
  width: number;
  height: number;
  blur: string;
}

export const WIDTHS = [${WIDTHS.join(', ')}] as const;

export const IMAGES: Record<string, ImageAsset> = {
${body},
};

/** \`/Homepage.png\` and \`homepage\` both resolve to the same asset key. */
export function imageKey(src: string): string {
  return src
    .replace(/^\\//, '')
    .replace(/\\.[a-z0-9]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function getImage(src: string): ImageAsset | undefined {
  return IMAGES[imageKey(src)];
}

export function srcSetFor(src: string): string {
  const key = imageKey(src);
  const asset = IMAGES[key];
  if (!asset) return '';
  return WIDTHS.filter((w) => w <= asset.width)
    .map((w) => \`/img/\${key}-\${w}.webp \${w}w\`)
    .join(', ');
}
`;

fs.writeFileSync(path.join(ROOT, 'lib/images.ts'), manifest);
console.log(`\nWrote lib/images.ts with ${entries.length} assets.`);
