import {refundBelongsToOrder} from '@/lib/payments/refunds';
import {NextRequest,NextResponse} from 'next/server';
import {requireAdmin} from '@/lib/admin';
import sql,{apiErrorResponse} from '@/lib/db';
import {fetchFlutterwaveRefund,refundCompleted} from '@/lib/payments/flutterwave';
import {reconcileOrderPoints} from '@/lib/loyalty/members';
export async function GET(){const gate=await requireAdmin('finance');if(gate.ok===false)return NextResponse.json({error:gate.error},{status:gate.status});try{const[refunds,exceptions,jobs,overdue]=await Promise.all([sql`SELECT * FROM order_refunds ORDER BY created_at DESC LIMIT 200`,sql`SELECT * FROM payment_receipts WHERE exception IS NOT NULL ORDER BY created_at DESC LIMIT 100`,sql`SELECT id,kind,status,attempts,last_error,created_at FROM notification_jobs WHERE status IN ('failed','pending','processing') ORDER BY created_at DESC LIMIT 100`,sql`SELECT id,payment_ref,payment_provider,created_at FROM ritual_orders WHERE status IN ('pending','awaiting_payment') AND payment_expires_at<NOW()-INTERVAL '30 minutes' ORDER BY created_at LIMIT 100`]);return NextResponse.json({refunds,exceptions,jobs,overdue});}catch(err){const{status,error}=apiErrorResponse(err);return NextResponse.json({error},{status});}}
export async function POST(req:NextRequest){const gate=await requireAdmin('finance');if(gate.ok===false)return NextResponse.json({error:gate.error},{status:gate.status});try{const body=await req.json();const id=String(body.id||'');if(!/^[0-9a-f-]{36}$/i.test(id))return NextResponse.json({error:'Valid refund ID required.'},{status:400});
  if(!['reconcile','resolve-exception','retry-notification'].includes(body.action))return NextResponse.json({error:'Choose a supported finance action.'},{status:400});
  if(body.action==='resolve-exception'){const reference=String(body.reference||'').trim().slice(0,120);const transactionId=String(body.transactionId||'');if(!reference||!transactionId)return NextResponse.json({error:'Record the external return or reconciliation reference and transaction ID.'},{status:400});const updated=await sql`UPDATE payment_receipts SET exception=NULL,resolution_reference=${reference},resolved_at=NOW() WHERE order_id=${id}::uuid AND transaction_id=${transactionId} AND exception IS NOT NULL RETURNING transaction_id`;if(!updated.length)return NextResponse.json({error:'Payment exception changed or was already resolved. Refresh and retry.'},{status:409});await sql`INSERT INTO admin_audit(actor,action,subject,detail) VALUES(${gate.actor},'payment.exception-resolved',${id},${JSON.stringify({reference,transactionId})}::jsonb)`;return NextResponse.json({ok:true});}
  if(body.action==='retry-notification'){const updated=await sql`UPDATE notification_jobs SET status='pending',attempts=0,available_at=NOW() WHERE id=${id}::uuid AND status='failed' RETURNING id`;if(!updated.length)return NextResponse.json({error:'Notification is no longer failed. Refresh and retry.'},{status:409});await sql`INSERT INTO admin_audit(actor,action,subject) VALUES(${gate.actor},'notification.retry',${id})`;return NextResponse.json({ok:true});}
  const[refund]=await sql`SELECT * FROM order_refunds WHERE id=${id}::uuid`;if(!refund)return NextResponse.json({error:'Refund not found.'},{status:404});const reference=String(body.reference||refund.provider_reference||'').trim().slice(0,120);
  if(refund.provider==='flutterwave'){if(!reference)return NextResponse.json({error:'Enter the provider refund ID for reconciliation.'},{status:400});const result=await fetchFlutterwaveRefund(reference);if(!result||!refundCompleted(result.status)||result.amount!==Number(refund.amount_ngn)||!await refundBelongsToOrder(String(refund.order_id),result.transactionId))return NextResponse.json({error:'Provider has not confirmed this order, refund amount and completion.'},{status:409});}
  else if(!reference)return NextResponse.json({error:'Bank refund evidence/reference is required.'},{status:400});
  await sql`SELECT c24_complete_refund(${id}::uuid,${reference})`;await reconcileOrderPoints(String(refund.order_id));await sql`INSERT INTO admin_audit(actor,action,subject,detail) VALUES(${gate.actor},'refund.reconciled',${id},${JSON.stringify({reference})}::jsonb)`;return NextResponse.json({ok:true});
}catch(err){const{status,error}=apiErrorResponse(err,'Could not reconcile refund.');return NextResponse.json({error},{status});}}
